### ISSUE TITLE
Weird scrollbars effect

### ISSUE THREAD

**Issue by manuelcanepa** [mageplaza/magento-2-reports#13]
The reports shows and hide scrollbars constantly

### Preconditions
1. Magento: 2.3.2
2. PHP: 7.2.20
3. MySQL: 10.3.7-MariaDB

### Steps to reproduce
1. Login on backend
2. Go to dashboard

### Expected result
1. Static graph

### Actual result
1. https://imgur.com/a/UnAm8FQ

**Comment by Shinichi69** [comment]
Hi @manuelcanepa 

I’m Shin from Mageplaza.com and I will support you on this issue.

On your problem, you just need to click on the arrow icon and change the size of the chart.
Please see this screenshot:
- http://prntscr.com/qhrodi

Thank you!

**Comment by Shinichi69** [comment]
Closed due to no response within 7 days.
