### ISSUE TITLE
Sales by Location Card

### ISSUE THREAD

**Issue by eurobeautiful** [mageplaza/magento-2-reports#15]
The sales by location card just shows the spinning icon. I disabled the card, and then when I try to enable it again I get this error message:

Warning: Division by zero in app/code/Mageplaza/Reports/Block/Dashboard/SalesByLocation.php on line 124

### Preconditions

1. Magento: 2.3.4
2. PHP: 7.2
3. MySQL: 5.7

### Steps to reproduce

1. As per description above

### Expected result

1. As per description above

### Actual result

1. As per description above

**Comment by Shinichi69** [comment]
Hi @eurobeautiful 

I’m Shin from Mageplaza and I will support you on this issue.
I have already received your issue reports and I am sorry for that.

To solve the problem, please download and replace this file follow the path:
-app/code/Mageplaza/Reports/Block/Dashboard/SalesByLocation.php
Then please check again and let me know the result.

Thank you!
[SalesByLocation.zip](https://github.com/mageplaza/magento-2-reports/files/4777691/SalesByLocation.zip)

**Comment by eurobeautiful** [comment]
Thank you. I will test it and let you know if we have other problems.
