### ISSUE TITLE
Incorrect Year To Date (YTD) Calculation

### ISSUE THREAD

**Issue by eurobeautiful** [mageplaza/magento-2-reports#16]
When selecting the options YTD and 2YTD the date range is incorrect. It selects a one-year (or two year range). For example if today is June 12, 2020, it selects June 12, 2019 as the start date.

That's incorrect. YTD means "year to date", which means the start date is always January 1. When selecting YTD it would be January 1 of the current year, when using 2YTD it would be January 1 of last year.

https://en.wikipedia.org/wiki/Year-to-date
https://www.investopedia.com/terms/y/ytd.asp

**Comment by Shinichi69** [comment]
Hi @eurobeautiful 

I’m Shin from Mageplaza and I will support you on this ticket.
I have already received your issue reports and I am sorry for that.

With our extension, with YTD and 2YTD options, it will be calculated from the current time to the same day of one or two years ago.

If you have any questions, please contact me via this ticket.
Thank you!

**Comment by eurobeautiful** [comment]
That's incorrect, but it's your module if you don't want to fix it.
