### ISSUE TITLE
Comparison periods not working

### ISSUE THREAD

**Issue by eurobeautiful** [mageplaza/magento-2-reports#17]
The default view (Previous Period) works well.

But when I change the comparison date to either Previous Year of Custom Range, the indicator shows the correct date, but the data in the charts don't change.

**Comment by Shinichi69** [comment]
Hi @eurobeautiful 

I’m Shin from Mageplaza and I will support you on this issue.
I have already received your issue reports and I am sorry for that.

To solve the problem, please download and replace this file:
- app/code/Mageplaza/Reports/view/base/web/js/dashboard/initDateRange.js
Then please run the upgrade and deploy command again.

Thank you so much!
[initDateRange.zip](https://github.com/mageplaza/magento-2-reports/files/4778420/initDateRange.zip)

**Comment by eurobeautiful** [comment]
Thank you, we will test it and let you know if we have other problems.
