### ISSUE TITLE
Error after installation Dont work in 2.3.3 or 2.2.11

### ISSUE THREAD

**Issue by frangoncru** [mageplaza/magento-2-reports#22]
I installed the module in varios magento versions 2.2.11 and 2.3.3 and in all them i have an error im not able to access to the admin because have 3 errors exceptions 

### Preconditions (*)

1. Magento: 2.3.3
2. PHP: 7.1

### Steps to reproduce (*)

1.I install the mageplaza-core
2.I install the module through the composer and everything is ok

### Expected result (*)

1. [Enter to the admin and see the module working]
2.

### Actual result (*)

1. 3 exception(s):
Exception #0 (ReflectionException): Class Mageplaza\Reports\Helper\Data does not exist
Exception #1 (ReflectionException): Class Mageplaza\Reports\Helper\Data does not exist
Exception #2 (ParseError): syntax error, unexpected '='
2.[Screenshot of the error https://pasteboard.co/JszPnDx.png]

**Comment by Shinichi69** [comment]
Hi @frangoncru 

I checked your problem on my local with the conditions you mentioned.
However, I was able to install the extension successfully and the extension still works fine.

Please try again.

Thanks so much!

**Comment by frangoncru** [comment]
Hi@Shinichi69

I make another installation over magento 2.2.4 PHP 7.0.33 
Now i receive this error

Class Mageplaza\Reports\Helper\Data does not exist

Can you help me please i really need this extension working.

Thanks

**Comment by Shinichi69** [comment]
Hi @frangoncru 

I checked my local again with the information you provided.
However, I was able to install successfully without any problems.

You can try to install the extension using our solution 1 following this guide:
- https://www.mageplaza.com/install-magento-2-extension/#solution-1-ready-to-paste

Thanks so much!

**Comment by Shinichi69** [comment]
Closed due no response within 7 days.
