### ISSUE TITLE
dashboard reports loads very slow after updating from 1.2.2 ver.

### ISSUE THREAD

**Issue by Nessniko** [mageplaza/magento-2-reports#23]
After we update from 1.2.2
to 1.3.3
the dashboard load data of the report very slow.
on 1.2.2 it was very quick..
anyway to solve it ?

**Comment by Shinichi69** [comment]
Hi @Nessniko 

Please go to Reports->Mageplaza Reports->Refresh Statistics.
- https://prnt.sc/up16wu
- https://prnt.sc/up172f
Then reindex the data and check again.

Thanks so much!

**Comment by Nessniko** [comment]
Hi

I don’t have the reports as you sent, no Mageplaza Reports under reports.

Screenshot attached :




And the dashboard still the same after refreshing general report statestic >

It looks like that :




The wheels are turning long time and take time to updated statistics.
We didn’t face it with ver. 1.2.2.

Please advise…

thanks

Ness
סול - SOL







WWW.SEEDOFLIFE.SHOP <https://www.psytshirt.com/>

**Comment by Shinichi69** [comment]
Hi @Nessniko 

I'm sorry I mistook the feature of the Reports Pro version.

Please give me the Magento version you are using so I can recheck this issue on my local.

Thanks so much!

**Comment by Nessniko** [comment]
Hi
Magento ver. 2.3.5-p1

**Comment by Shinichi69** [comment]
Hi @Nessniko 

I checked your problem again with Magento 2.3.5-p1.
However, the extension is still working well.

The cards still load data quickly.

Thanks so much!

**Comment by Nessniko** [comment]
Hi @Shinichi69 
Please check our experience 
https://streamable.com/6v8edk

and we tested it on 3 different environments.
on previous ver the statistics were super fast and now its slow.

**Comment by Shinichi69** [comment]
Hi @Nessniko 

Regarding your issue, please create a ticket and provide us with your site information on that ticket and I will check your issue.
- https://mageplaza.freshdesk.com/support/tickets/new

Thanks so much!

**Comment by Nessniko** [comment]
Hi @Shinichi69 

ticket placed : #103776 report issue

thanks

**Comment by Shinichi69** [comment]
Hi @Nessniko 

Please follow the ticket you created and I will assist you in this issue.

And I will close this issue.

Thanks so much!
