### ISSUE TITLE
Error after Installation in Magento 2.4

### ISSUE THREAD

**Issue by wajahatbashir** [mageplaza/magento-2-reports#24]
### Preconditions (*)

1. Magento Version 2.4

### Steps to reproduce (*)

1. Error: Fatal error: Class 'Mageplaza\Core\Helper\AbstractData' not found in app\code\Mageplaza\Reports\Helper\Data.php on line 45

### Expected result (*)

1. https://prnt.sc/utbb5k

### Actual result (*)

1. Due to this error I can't open Magento admin.

**Comment by Shinichi69** [comment]
Hi @wajahatbashir 

I’m Shin from Mageplaza and I will support you on this issue.

For your problem, please install our Core extension:
- https://github.com/mageplaza/module-core

Then please check again.

Thanks so much!

**Comment by Shinichi69** [comment]
Closed due no response within 7 days.
