### ISSUE TITLE
$card->getDetailUrl() is empty

### ISSUE THREAD

**Issue by slowhand11** [mageplaza/magento-2-reports#27]
### Preconditions (*)

1. 2.3.2

### Steps to reproduce (*)

1.reproduceable in Dashbord. When clicking "view details" it opens a new window and it shows dashboard again. No Detail View.

### Expected result (*)

1. [Screenshots, logs or description]
2. Expecting to see details

### Actual result (*)
Link has empty href, it opens a new window only
```
`<div class="dashboard-item-header">
        <div class="dashboard-item-title">Sales By Location</div>
                <div class="view-detail">
                        <a href="" target="_blank">Details anzeigen</a>
                 </div>
         <div style="clear: both"></div>
</div>`
```

**Comment by TeddyMageplaza** [comment]
Hello,

I am Teddy from Mageplaza Support Team.

I have already received your issue report. But when I install Reports modules with Magento 2.3.2, they work properly.
And please note that you should clean the cache after installing Reports modules.

Or can you send me some screenshots of this problem to clarify it?
Looking forward to hearing from you.
Thanks so much!

**Comment by slowhand11** [comment]
Hi,
thanks for reply. Ive updated my initial description with the code. I have cleaned cache after installing.

**Comment by huykuy99** [comment]
Hi,

Are you using the Reports Standard Free version? The Standard version is unable to "View details".
You should upgrade to our Reports Professional to experience more functionality.

You can refer to the following links:

1. https://docs.mageplaza.com/reports/index.html
2. https://i.imgur.com/huagcmN.png
3. https://www.mageplaza.com/magento-2-reports-extension/

Thank you so much!

**Comment by TeddyMageplaza** [comment]
Closed due to no response within 7 days.
