### ISSUE TITLE
Resource Permission is not working

### ISSUE THREAD

**Issue by alitopaloglu** [mageplaza/magento-2-reports#28]
### Preconditions (*)

1. v2.4.2
2. on replaced dashboard of mageplaza

### Steps to reproduce (*)

1. Create a new user group without magento dashboard and mageplaza dashboard permissions
2. Login as this user group

### Expected result (*)

1. User must not be able to see mageplaza or magento dashboard

### Actual result (*)

1. User is able to see mageplaza dashboard
2. https://www.dropbox.com/s/3j8vsotxbg6qot7/Screen%20Shot%202021-03-24%20at%2019.09.04.png?dl=0
3. https://www.dropbox.com/s/iyv9su7t7xjfy34/Screen%20Shot%202021-03-24%20at%2019.09.36.png?dl=0

Edit-1: After opening user roles and just saving without changing anything, users are getting redirected to mpreports/dashboard page and see an error about permissions. Before installing this module that users was seeing catalog/products because magento redirecting them to here, because they have no permission for dashboard

I think if both magento dashboard and mageplaza dashboard permissions are not set for a user group, this module must not override anything for dashboard and just redirect to user what magento redirects it before

Edit-2: I think that code

`public function afterGetStartupPageUrl(Url $url, $result)
    {
        if ($this->_helperData->isEnabledDashboard()) {
            $result = 'mpreports/dashboard';
        }
        return $result;
    }`

must be something like 

`public function afterGetStartupPageUrl(Url $url, $result)
    {
        if ($this->_helperData->isEnabledDashboard() AND USER HAS REQUIRED PERMISSIONS FOR DASHBOARD) {
            $result = 'mpreports/dashboard';
        }
        return $result;
    }`

Edit-3: And also same change is needed here as well
Mageplaza\Reports\Plugin\BackendLogoUrl

**Comment by TeddyMageplaza** [comment]
Hi @alitopaloglu,

First of all, thank you for the issue report.

I am Teddy from Mageplaza Support Team.
I am checking this issue and will get back to you as soon as possible.

Have a nice day!

**Comment by TeddyMageplaza** [comment]
Hi @alitopaloglu,

First of all, we are deeply grateful for your kind patience.

- https://i.imgur.com/hwLUOG1.png

Secondly, we cannot reproduce this problem on our local site although we have tested your problem many times with different roles. All results showed that our extensions work properly.
 And because it related to "ADMIN_RESOURCE" at "Mageplaza/Reports/Controller/Adminhtml/Dashboard/Index.php" file, you can refer to my code, I think it will help you:

- https://i.imgur.com/YvAoWVC.png

Thank you so much!

**Comment by TeddyMageplaza** [comment]
Closed due to no response within 7 days.
