### ISSUE TITLE
wrong data in reports

### ISSUE THREAD

**Issue by purpletreesoft** [mageplaza/magento-2-reports#4]
The dashboard shows average sales in place of total sales. i.e. it shows the same number for total sales and average sales.
pls see the image https://prnt.sc/kre1jq

**Comment by thaimageplaza** [comment]
Hi,
What version are you using?
I am using Magento 2.2.4, Reports extension 1.1.0 and It working normally.
http://prntscr.com/krjhxl.
Please check again.

**Comment by purpletreesoft** [comment]
I am on 2.2.5, and on the latest version of this extension via composer.

**Comment by thaimageplaza** [comment]
Hi,
I am sorry for that,
Please update code in file "LifetimeSales.php" 
(path: \mageplaza\module-reports\Block\Dashboard\LifetimeSales.php)
`<?php
/**
 * Mageplaza
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Mageplaza.com license that is
 * available through the world-wide-web at this URL:
 * https://www.mageplaza.com/LICENSE.txt
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade this extension to newer
 * version in the future.
 *
 * @category    Mageplaza
 * @package     Mageplaza_Reports
 * @copyright   Copyright (c) Mageplaza (https://www.mageplaza.com/)
 * @license     https://www.mageplaza.com/LICENSE.txt
 */

namespace Mageplaza\Reports\Block\Dashboard;

/**
 * Class LifetimeSales
 * @package Mageplaza\Reports\Block\Dashboard
 */
class LifetimeSales extends AbstractClass
{
    const NAME = 'lifetimeSales';

    /**
     * @return \Magento\Framework\Phrase|string
     */
    public function getTitle()
    {
        return __('Lifetime Sales');
    }

    /**
     * @return string
     * @throws \Magento\Framework\Exception\LocalizedException
     */
    public function getTotal()
    {
        $total = $this->_helperData->getLifetimeSales();
        if (isset($total['lifetime'])) {
            return $this->format($total['lifetime']);
        }
        \Zend_Debug::dump($total);
        return parent::getTotalLabel();
    }
}`
Thank you very much!

**Comment by purpletreesoft** [comment]
thanks, works fine now.
btw I am surprised how it worked for you, with the wrong variable. magic.

**Comment by thaimageplaza** [comment]
Hi,
That's our fault. We will update it in next patch.
