### ISSUE TITLE
how to display the total qty about order

### ISSUE THREAD

**Issue by benyang2015** [mageplaza/magento-2-reports#7]
### Preconditions

1. Magento: 
2. PHP: 
3. MySQL: 
4. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by thaimageplaza** [comment]
Hi,
I’m not sure that I can understand your question.
Please explain your question more clearly. Thank you!

**Comment by benyang2015** [comment]
<img width="419" alt="11" src="https://user-images.githubusercontent.com/15188607/53070191-459ecb80-3519-11e9-8123-06154eb0a4ac.png">
items ordered qty

**Comment by thaimageplaza** [comment]
Hi,
Which extension are you using?
Our Report extension doesn't support for functions you give.
Our interface must look like the image below
![image](https://user-images.githubusercontent.com/40683842/53072043-906b1400-3516-11e9-803d-41f063db29a8.png)

**Comment by benyang2015** [comment]
I use aheadwork advanced report
they can display items ordered qty .
mageplaza report can support this function or not?
It must have

**Comment by thaimageplaza** [comment]
Hi,
Yes, our extension can display items ordered qty.
You can install and use it.
Have a nice day!

**Comment by thaimageplaza** [comment]
Closed due to no response within 7 days.
