### ISSUE TITLE
Mobile dashboard: add default key + don't allow access when key is empty

### ISSUE THREAD

**Issue by Echron** [mageplaza/magento-2-reports#9]
After installing this (we installed another Mageplaze module that depends on this module for some reason) module, there is no access key in the configuration. This makes the mobile dashboard visible for anyone that goes to "mpreports/dashboard".

There should be 2 changes:
- when the access key is empty, don't allow access to the dashboard
- maybe add a default access key so there is already an access key upon installing this module

**Comment by NgoDuVietHung97** [comment]
Hi @Echron,

After installing our Reports extension, you show generate URL of the mobile dashboard:
![image](https://user-images.githubusercontent.com/32929797/64592265-d239aa00-d3d5-11e9-9fe7-469c6ac4fc10.png)

Then, the result will be like this: 
![image](https://user-images.githubusercontent.com/32929797/64592306-e4b3e380-d3d5-11e9-8b06-1ec521c89754.png)

Please refer here to know about your Reports extension:
http://docs.mageplaza.com/reports/index.html?_ga=2.40231906.1922292922.1568099251-269436255.1568099251

**Comment by Bang512** [comment]
Hi @Echron,

Sorry for the late response.
Thanks for your feedback. We will consider your idea in our next improvement to make our products better. 

Thank you very much!
